"""
Output directory management for organized session-based file storage
Creates timestamped folders for each crawl/analysis session
"""

import os
import logging
from datetime import datetime
from typing import Optional
from pathlib import Path

logger = logging.getLogger(__name__)


class OutputManager:
    """
    Manages organized output directories for web scraping and email generation.
    
    Structure:
    output/
      ├── domain.com_20260124_143022/
      │   ├── screenshots/
      │   ├── emails/
      │   ├── design_system.json
      │   └── summary.md
      └── domain.com_20260124_150133/
          └── ...
    """
    
    def __init__(self, domain: str, base_dir: str = "output", timestamp: Optional[str] = None):
        """
        Initialize output manager for a domain.
        
        Args:
            domain: Clean domain identifier (e.g., "shiseido.com-us-en")
            base_dir: Base output directory (default: "output")
            timestamp: Optional timestamp (auto-generated if not provided)
        """
        self.domain = domain
        self.base_dir = base_dir
        self.timestamp = timestamp or datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Create session folder: output/domain_YYYYMMDD_HHMMSS/
        self.session_dir = os.path.join(base_dir, f"{domain}_{self.timestamp}")
        
        # Subdirectories
        self.screenshots_dir = os.path.join(self.session_dir, "screenshots")
        self.emails_dir = os.path.join(self.session_dir, "emails")
        self.data_dir = os.path.join(self.session_dir, "data")
        
        logger.info(f"Output session: {self.session_dir}")
    
    def setup(self) -> str:
        """
        Create all necessary directories.
        
        Returns:
            Path to session directory
        """
        os.makedirs(self.screenshots_dir, exist_ok=True)
        os.makedirs(self.emails_dir, exist_ok=True)
        os.makedirs(self.data_dir, exist_ok=True)
        
        logger.info(f"Created output structure in: {self.session_dir}")
        return self.session_dir
    
    def get_screenshot_path(self, filename: str = None) -> str:
        """Get path for screenshot file"""
        if filename:
            return os.path.join(self.screenshots_dir, filename)
        return self.screenshots_dir
    
    def get_email_path(self, filename: str) -> str:
        """Get path for email template file"""
        return os.path.join(self.emails_dir, filename)
    
    def get_data_path(self, filename: str) -> str:
        """Get path for data file (JSON, etc.)"""
        return os.path.join(self.data_dir, filename)
    
    def get_summary_path(self) -> str:
        """Get path for summary markdown file"""
        return os.path.join(self.session_dir, "summary.md")
    
    def get_session_path(self, *paths) -> str:
        """Get path relative to session directory"""
        return os.path.join(self.session_dir, *paths)
    
    def create_summary(
        self,
        url: str,
        pages_crawled: int = 0,
        products_found: int = 0,
        emails_created: int = 0,
        design_system_extracted: bool = False,
        notes: str = ""
    ) -> str:
        """
        Create a summary.md file with session information.
        
        Returns:
            Path to created summary file
        """
        summary_path = self.get_summary_path()
        
        content = f"""# Web Scraping & Email Generation Summary

## Session Information
- **Date**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Domain**: {self.domain}
- **Source URL**: {url}

## Crawling Results
- **Pages Crawled**: {pages_crawled}
- **Products Found**: {products_found}
- **Design System Extracted**: {"✓ Yes" if design_system_extracted else "✗ No"}

## Generated Content
- **Email Templates Created**: {emails_created}

## File Structure
```
{self.domain}_{self.timestamp}/
├── screenshots/          # Full-page screenshots
├── emails/              # HTML email templates
│   ├── minimalist.html
│   ├── bold.html
│   └── elegant.html
├── data/                # Extracted data
│   ├── design_system.json
│   ├── products.json
│   └── crawl_data.json
└── summary.md           # This file
```

## Notes
{notes if notes else "_No additional notes_"}

---

Generated by ReasonLoop
"""
        
        with open(summary_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"Summary created: {summary_path}")
        return summary_path
    
    def get_info(self) -> dict:
        """Get session information as dictionary"""
        return {
            "domain": self.domain,
            "timestamp": self.timestamp,
            "session_dir": self.session_dir,
            "screenshots_dir": self.screenshots_dir,
            "emails_dir": self.emails_dir,
            "data_dir": self.data_dir,
        }


# Convenience function for use in abilities
def create_output_session(domain: str, timestamp: Optional[str] = None) -> OutputManager:
    """
    Create and setup an output session.
    
    Args:
        domain: Clean domain identifier
        timestamp: Optional timestamp (auto-generated if not provided)
    
    Returns:
        OutputManager instance with directories created
    """
    manager = OutputManager(domain, timestamp=timestamp)
    manager.setup()
    return manager


# Test example
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    
    # Example usage
    manager = create_output_session("shiseido.com-us-en")
    
    print("\nSession Info:")
    for key, value in manager.get_info().items():
        print(f"  {key}: {value}")
    
    print(f"\nScreenshot path: {manager.get_screenshot_path('homepage.png')}")
    print(f"Email path: {manager.get_email_path('minimalist.html')}")
    print(f"Data path: {manager.get_data_path('design_system.json')}")
    
    # Create summary
    manager.create_summary(
        url="https://www.shiseido.com/us/en/",
        pages_crawled=5,
        products_found=12,
        emails_created=3,
        design_system_extracted=True,
        notes="Successfully extracted brand colors and typography."
    )
    
    print(f"\nSummary created at: {manager.get_summary_path()}")
